### ISSUE TITLE
Schema with Zod Map is failing

### ISSUE THREAD

**Issue by ankitatdnv** [apvee/azure-functions-nodejs-monorepo#2]
Hi,

I am trying to use this package for creating Swagger documentation for Azure functions. But I am getting an error for a Schema which is using Zod Map:

``` typescript
export const PayloadSchema = z.object({
    projectId: z.string(),
    userId: z.string(),
    data: z.map(z.string(), z.string()),
    groupId: z.string(),
    requestId: z.string().optional(),
});
export type Payload = z.infer<typeof PayloadSchema>;
registerTypeSchema('Payload', PayloadSchema);
```

I am getting following Error while running the function:

```
Exception: {"message":"Unknown zod object type, please specify `type` and other OpenAPI props using `ZodSchema.openapi`.","data":{"currentSchema":{"valueType":{"_def":{"checks":[],"typeName":"ZodString","coerce":false}},"keyType":{"_def":{"checks":[],"typeName":"ZodString","coerce":false}},"typeName":"ZodMap"}}}
Stack: Error: {"message":"Unknown zod object type, please specify `type` and other OpenAPI props using `ZodSchema.openapi`.","data":{"currentSchema":{"valueType":{"_def":{"checks":[],"typeName":"ZodString","coerce":false}},"keyType":{"_def":{"checks":[],"typeName":"ZodString","coerce":false}},"typeName":"ZodMap"}}}
```

If I remove the zod map and use zod object instead, everything works fine.

**Comment by fabiofranzini** [comment]
Hi @ankitatdnv, since OpenAPI uses JSON Schema definitions to represent Zod structures, the serialization of a Zod schema containing z.map to JSON Schema is not natively supported. 
This limitation arises because JSON Schema lacks a direct representation for Map. In JSON, maps are typically represented as objects, so a Map cannot be directly translated. 
Each conversion requires adapting the Map structure into a standard object format where keys are treated as object properties.
